package api

const (
	MethodAdd           = "add"
	MethodAuth          = "auth"
	MethodBuildStream   = "build_stream"
	MethodCheck         = "check"
	MethodCleanStream   = "clean_stream"
	MethodCreate        = "create"
	MethodDelete        = "delete"
	MethodDownload      = "download"
	MethodGet           = "get"
	MethodInfo          = "info"
	MethodInstall       = "install"
	MethodIsPortBlock   = "is_port_block"
	MethodIsPkgEnable   = "is_pkg_enable"
	MethodList          = "list"
	MethodListShares    = "list_share"
	MethodPullStart     = "pull_start"
	MethodPullStatus    = "pull_status"
	MethodRemove        = "remove"
	MethodRename        = "rename"
	MethodRequest       = "request"
	MethodRestart       = "restart"
	MethodRun           = "run"
	MethodSet           = "set"
	MethodStart         = "start"
	MethodStartStream   = "start_stream"
	MethodStatus        = "status"
	MethodStop          = "stop"
	MethodStopStream    = "stop_stream"
	MethodRestartStream = "restart_stream"
	MethodUninstall     = "uninstall"
	MethodUpdate        = "update"
	MethodUpload        = "upload"
)
