package api

const (
	MethodCreate      = "create"
	MethodUpdate      = "update"
	MethodGet         = "get"
	MethodUpload      = "upload"
	MethodList        = "list"
	MethodListShares  = "list_share"
	MethodRename      = "rename"
	MethodInfo        = "info"
	MethodStart       = "start"
	MethodDelete      = "delete"
	MethodPullStart   = "pull_start"
	MethodPullStatus  = "pull_status"
	MethodCleanStream = "clean_stream"
	MethodStopStream  = "stop_stream"
	MethodStartStream = "start_stream"
	MethodBuildStream = "build_stream"
	MethodStatus      = "status"
	MethodInstall     = "install"
	MethodUninstall   = "uninstall"
	MethodRequest     = "request"
	MethodCheck       = "check"
	MethodIsPortBlock = "is_port_block"
	MethodAdd         = "add"
)
