---
name: Lint
on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "vendor/**"
      - ".github/workflows/**"

  pull_request:
    types: ["opened", "synchronize"]
    paths:
      - "**.go"
      - "vendor/**"
      - ".github/workflows/**"

jobs:
  golangci-lint:
    name: GolangCI Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go mod download
      - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: "v1.59"
          args: -v
